//! Sprite project → buildable Cargo project.
//!
//! Pipeline:
//!   1. Parse the studio's `*.warpforge.json`.
//!   2. For each sprite, parse `scripts_xml` (the Blockly XML the studio
//!      writes) into a `ScriptNode` tree.
//!   3. Set each sprite's `compiledScripts` field to the resulting JSON.
//!   4. Emit `out_dir/Cargo.toml` + `out_dir/src/main.rs` + `out_dir/project.json`.
//!
//! `cargo build --release` in the output dir produces a single native
//! binary that, when run, displays the sprite stage and starts the
//! green-flag scripts immediately.

pub mod xml;

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{anyhow, Context, Result};
use serde_json::Value as JsonValue;

use wf_sprite_runtime::ScriptNode;

/// Compile `project_json` (the contents of a *.warpforge.json file) into a
/// buildable Cargo project at `out_dir`. Returns the absolute path to the
/// generated project root.
///
/// `runtime_dep` controls how the generated Cargo.toml depends on
/// `wf-sprite-runtime`. Use `RuntimeDep::Path` during local development
/// so changes to the runtime are picked up; use `RuntimeDep::Version` when
/// shipping a binary that should be reproducible from crates.io.
pub fn compile_to_dir(
    project_json: &str,
    out_dir: &Path,
    runtime_dep: RuntimeDep,
) -> Result<PathBuf> {
    let mut project: JsonValue =
        serde_json::from_str(project_json).context("parse project JSON")?;

    // Walk every sprite, transcompile its scripts_xml.
    if let Some(stage) = project.get_mut("stage_state").and_then(|v| v.as_object_mut()) {
        if let Some(sprites) = stage.get_mut("sprites").and_then(|v| v.as_array_mut()) {
            for sprite in sprites {
                let xml = sprite
                    .get("scripts_xml")
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .to_string();
                let nodes = if xml.trim().is_empty() {
                    Vec::new()
                } else {
                    xml::parse_scripts_xml(&xml)?
                };
                let nodes_json = serde_json::to_value(&nodes)?;
                if let Some(obj) = sprite.as_object_mut() {
                    obj.insert("compiledScripts".into(), nodes_json);
                }
            }
        }
    }

    // Pull a sane crate name + window title from the project metadata.
    let app_name = project
        .get("project")
        .and_then(|p| p.get("app_name").or_else(|| p.get("appName")))
        .and_then(|v| v.as_str())
        .unwrap_or("sprite_app")
        .to_string();
    let crate_name = sanitize_crate_name(&app_name);

    fs::create_dir_all(out_dir).with_context(|| format!("create {}", out_dir.display()))?;
    fs::create_dir_all(out_dir.join("src"))?;

    // project.json — what the runtime reads.
    let pretty = serde_json::to_string_pretty(&project)?;
    fs::write(out_dir.join("project.json"), pretty)?;

    // Cargo.toml.
    let runtime_dep_line = match runtime_dep {
        RuntimeDep::Path(path) => format!(
            "wf-sprite-runtime = {{ path = \"{}\" }}",
            path.display()
        ),
        RuntimeDep::Version(v) => format!("wf-sprite-runtime = \"{}\"", v),
    };
    let cargo_toml = format!(
        r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "{crate_name}"
path = "src/main.rs"

[dependencies]
{runtime_dep_line}
"#
    );
    fs::write(out_dir.join("Cargo.toml"), cargo_toml)?;

    // src/main.rs — bakes project.json into the binary so it's
    // self-contained after `cargo build`.
    let main_rs = r#"// Auto-generated by wf-sprite-codegen.
// Re-run codegen on the studio side to regenerate.

const PROJECT_JSON: &str = include_str!("../project.json");

fn main() {
    wf_sprite_runtime::run_project_json(PROJECT_JSON);
}
"#;
    fs::write(out_dir.join("src/main.rs"), main_rs)?;

    Ok(fs::canonicalize(out_dir)?)
}

/// How the generated Cargo.toml refers to `wf-sprite-runtime`.
pub enum RuntimeDep {
    /// `path = "..."` — local dev. Pass an absolute path to the
    /// `crates/wf-sprite-runtime` directory.
    Path(PathBuf),
    /// `"x.y.z"` — crates.io reference. Use when shipping reproducible
    /// builds.
    Version(String),
}

/// Sanitize an arbitrary app name into a valid Rust crate identifier.
fn sanitize_crate_name(name: &str) -> String {
    let mut out = String::new();
    for c in name.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_lowercase());
        } else if c == ' ' || c == '-' || c == '_' {
            if !out.ends_with('_') && !out.is_empty() {
                out.push('_');
            }
        }
    }
    while out.ends_with('_') {
        out.pop();
    }
    if out.is_empty() {
        out.push_str("sprite_app");
    }
    if out.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
        out.insert(0, '_');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn crate_name_sanitization() {
        assert_eq!(sanitize_crate_name("Sprite Bouncer"), "sprite_bouncer");
        assert_eq!(sanitize_crate_name("123app"), "_123app");
        assert_eq!(sanitize_crate_name("__weird-Name__"), "weird_name");
        assert_eq!(sanitize_crate_name(""), "sprite_app");
    }

    #[test]
    fn compiles_minimal_project() {
        let json = serde_json::json!({
            "schema_version": 1,
            "project": {
                "id": "x", "app_name": "Tiny", "package_id": "x",
                "version": "0.1", "author": "t", "description": "",
                "target_type": "desktop_slint", "theme": "auto",
                "created_at": "", "updated_at": ""
            },
            "workspace_state": {},
            "normalized_graph": { "nodes": [], "edges": [] },
            "assets": [], "ai_history": [],
            "stage_state": {
                "schema_version": 1,
                "sprites": [{
                    "id": "s1", "name": "S",
                    "x": 0, "y": 0, "direction": 90, "size": 100,
                    "visible": true, "rotationStyle": "all-around",
                    "costumeIndex": -1, "costumes": [], "sounds": [],
                    "scripts_xml": "",
                    "variables": {}, "lists": {}, "layer": 1
                }],
                "backdropIndex": -1, "backdrops": [],
                "globalVariables": {}, "globalLists": {}
            },
            "settings": {}
        }).to_string();

        let tmp = tempfile::TempDir::new().unwrap();
        let out = compile_to_dir(&json, tmp.path(), RuntimeDep::Version("0.1".into())).unwrap();
        assert!(out.join("Cargo.toml").exists());
        assert!(out.join("src/main.rs").exists());
        assert!(out.join("project.json").exists());

        let cargo = std::fs::read_to_string(out.join("Cargo.toml")).unwrap();
        assert!(cargo.contains("name = \"tiny\""));
        let main = std::fs::read_to_string(out.join("src/main.rs")).unwrap();
        assert!(main.contains("run_project_json"));
    }
}

/// Re-export so consumers of this crate don't have to depend on the
/// runtime separately just to construct ScriptNodes for tests.
pub use wf_sprite_runtime::ScriptNode as RuntimeScriptNode;

/// Convenience: parse just the `scripts_xml` portion. Useful in tests
/// and from a Tauri command that wants to preview the JSON form.
pub fn parse_xml_to_nodes(xml: &str) -> Result<Vec<ScriptNode>> {
    xml::parse_scripts_xml(xml).map_err(|e| anyhow!("parse XML: {e}"))
}
